config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'
  get 'api/drivers'

  get 'api/customers'

  root to: 'customers#index'
  get 'customers', to: 'customers#index'
  post 'customers', to: 'customers#create'
  
  get 'drivers', to: 'drivers#index'
  get 'dashboard', to: 'dashboard#index'


  scope '/api' do
    scope '/v1' do
      scope '/drivers' do
        post '/' => 'api#drivers'
      end
      scope '/customers' do
        post '/' => 'api#customers'
      end
      scope '/rides' do
        post '/' => 'api#all_rides'
        post '/waiting' => 'api#new_rides'
        post '/ongoing' => 'api#ongoing_rides'
        post '/completed' => 'api#completed_rides'
        post '/accept' => 'api#accept_ride'
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/response.rb
module Response
    def json_response(object, status = :ok)
        render json: object, status: status
    end
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id             :integer          not null, primary key
#  requested_ride :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Customer < ApplicationRecord
    has_many :rides
end

app/models/driver.rb
# == Schema Information
#
# Table name: drivers
#
#  id            :integer          not null, primary key
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  accepted_ride :boolean          default(FALSE)
#

class Driver < ApplicationRecord
    has_many :rides
end

app/models/ride.rb
# == Schema Information
#
# Table name: rides
#
#  id              :integer          not null, primary key
#  time            :datetime
#  location        :string
#  status          :integer          default("waiting")
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  driver_id       :integer
#  customer_id     :integer
#  ride_start_time :datetime
#  ride_end_time   :datetime
#

class Ride < ApplicationRecord
  enum status: [:waiting, :ongoing, :completed]
  belongs_to :customer
  belongs_to :driver, optional: true
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  before_action :check_driver_id, only: [
                                  :ongoing_rides,
                                  :completed_rides,
                                  :drivers
                                ]

  before_action :check_customer_id, only: :customers
  before_action :set_driver_id, only: :drivers
  before_action :set_customer_id, only: :customers
  before_action :sanitize_accept_ride, only: :accept_ride

  def drivers
    @driver = Driver.find(set_driver_id)

    render json: @driver.to_json(:include => :rides)

  end

  def customers
    @customer = Customer.find(set_customer_id)

    render json: @customer.to_json(:include => :rides)
  end

  def all_rides
    @rides = Ride.all

    render json: @rides
  end

  def new_rides
    @rides = Ride.where(status: :waiting) 

    render json: @rides
  end

  def ongoing_rides
    @rides = Ride.where(status: :ongoing, driver_id: params[:driverId])

    render json: @rides
  end

  def completed_rides
    @rides = Ride.where(status: :completed, driver_id: params[:driverId])

    render json: @rides
  end

  def accept_ride
    @ride = Ride.find(sanitize_accept_ride[:ride_id])
    @driver = Driver.find(sanitize_accept_ride[:driver_id])
    if (@driver.accepted_ride === true)
      render json: {
        message: "Driver already has ride"
      }, status: 422
      return
    end
    if @ride.status === "waiting" && @ride.driver_id == nil
        @ride.driver_id = sanitize_accept_ride[:driver_id]      
        @ride.ride_start_time = Time.now
        @ride.ride_end_time = 5.minutes.from_now
        @ride.driver.accepted_ride = true
        @ride.status = :ongoing
        if (@ride.driver.save! && @ride.save!)
          ProcessRideWorker.perform_in(30.seconds, @ride.id)
          flash[:notice] = "Trip started"
          render json: {
            ride: @ride,
            message: "Ride started"
          }, status: 200
        else
          flash[:error] = "Something went wrong"
          render json: {
            message: "Something went wrong"
          }, status: 422
        end
      else
        flash[:error] = "Something went wrong"
        render json: {
          message: "Something went wrong"
        }, status: 422
      end
  end


  private

  def check_driver_id
    if !params[:driverId]
      render json: {
        message: "Bad Request: Param driverId missing", 
        status: 422 
      }, status: :unprocessable_entity
    else
      true
    end
  end

  def check_customer_id
    if !params[:customerId]
      render json: {
        message: "Bad Request: Param customerId missing", 
        status: 422 
      }, status: :unprocessable_entity
    else
      true
    end
  end

  def set_customer_id
    params[:customerId]
  end

  def set_driver_id
    params[:driverId]
  end

  def sanitize_accept_ride
    params.require(:ride).permit(:customer_id, :driver_id, :ride_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :customer_params, only: :create

  def index
    @customer = Customer.new
  end

  def create
    @customer = Customer.find_or_initialize_by(customer_params)
    respond_to do |format|
      @ride = @customer.rides.new
      if @ride.save!
        ActionCable.server.broadcast 'new_rides', @ride 
        format.html { redirect_to customers_path, notice: 'Ride was successfully requested' }
        format.json {
          render json: @ride
        }
      else
        format.html { redirect_to customers_path, error: 'Could not request ride' }
      end
    end
  end


  private

  def customer_params
    params.require(:customer).permit(:id)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        @rides = Ride.all
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
    before_action :set_driver_id, only: :index
    
    def index
        if !set_driver_id
            @driver = Driver.all
            render template: 'drivers/all'
        else
            begin
                @waitingRides = Ride.where(status: :waiting)
                @driver = Driver.includes(:rides).find(set_driver_id)
                @ongoingRides = Ride.where(status: :ongoing, driver_id: set_driver_id)
                @completedRides = Ride.where(status: :completed, driver_id: set_driver_id)
            rescue ActiveRecord::RecordNotFound
                flash[:error] = "No Such driver"
                redirect_to drivers_path
            end
        end
    end


    private

    def set_driver_id
        params[:id]
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/dashboard/index_helper.rb
module Dashboard::IndexHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/customers/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">  
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:notice] %>
    </div>
<% elsif flash[:error] %>
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:error] %>
    </div>
<% end %>

<div class="row align-items-center customer_form">
    <div class="col-6 offset-3">
        <%= simple_form_for @customer, remote: true do |f| %>
            <%= f.input :id, placeholder: 'Customer Id', label: false %>
            <%= f.button :submit, "Find Ride", class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1> <%= link_to "Refresh", request.original_fullpath  %>


<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Request Id</th>
        <th>Customer Id</th>
        <th>Time Elapsed</th>
        <th>Status</th>
        <th>Driver</th>
    </tr>
    </thead>
    <tbody>
    <% @rides.each_with_index do |ride, i| %>
        <tr>
            <th scope="row"><%= i+1 %></th>
            <td><%= ride.id %></td>
            <td><%= ride.customer_id %></td>
            <td><%= distance_of_time_in_words(ride.created_at, Time.now) %></td>
            <td><%= ride.status.to_s %></td>
            <td><%= ride.driver_id %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/drivers/all.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">  
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:notice] %>
    </div>
<% elsif flash[:error] %>
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:error] %>
    </div>
<% end %>

<h1>All driver listing</h1>

app/views/drivers/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">  
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:notice] %>
    </div>
<% elsif flash[:error] %>
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:error] %>
    </div>
<% end %>
    <%= javascript_tag "driverId = #{params[:id] || 0} " %>
    <h1>Driver Page <%= params[:id] %></h1> <%= link_to "Refresh", request.original_fullpath  %>
<div class="flex col-md-10">
    <div class="col-md-3 inline">
        <div class="head">
            Waiting
        </div>
        <div class="wait body">
            <% @waitingRides.each do |ride| %>
                <div class="card" id="card-<%= ride.id %>">
                    <div class="card-block">
                        <div class="card-title">
                            <span class="left">Req Id: <%= ride.id %></span>
                            <span class="right">Customer Id: <%= ride.customer_id %></span>
                        </div>
                        <p class="card-text"><%= distance_of_time_in_words(ride.created_at, Time.now) %></p>
                        <%= simple_form_for :ride, {url: accept_path, remote: true} do |f| %>
                            <%= f.hidden_field :customer_id, value: ride.customer_id %>
                            <%= f.hidden_field :driver_id, value: params[:id] %>
                            <%= f.hidden_field :ride_id, value: ride.id %>
                            <%= f.button :submit, "Select", class: 'btn btn-primary' %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>

    </div>
    <div class="col-md-3 inline">
        <div class="head">
            Ongoing
        </div>
        <div class="body">
            <% @ongoingRides.each do |ride| %>
                <div class="card" id="card-<%= ride.id %>">
                    <div class="card-block">
                        <div class="card-title">
                            <span class="left">Req Id: <%= ride.id %></span>
                            <span class="right">Customer Id: <%= ride.customer_id %></span>
                        </div>
                        <p class="card-text">started <%=  distance_of_time_in_words(Time.now, ride.ride_start_time || ride.time)  %></p>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
        <div class="col-md-3 inline">
        <div class="head">
            Completed
        </div>
        <div class="body">
            <% @completedRides.each do |ride| %>
                <div class="card" id="card-<%= ride.id %>">
                    <div class="card-block">
                        <div class="card-title">
                            <span class="left">Req Id: <%= ride.id %></span>
                            <span class="right">Customer Id: <%= ride.customer_id %></span>
                        </div>
                        <p class="card-text"><%= distance_of_time_in_words(ride.ride_end_time, Time.now) %></p>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ola</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid outer-padding <%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>